image: "python:3.9"

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - pip install -e .

pytest:
  image: $IMAGE
  parallel:
    matrix:
      - IMAGE: ['python:3.7', 'python:3.10']
  stage: test
  script:
  - ( cd examples/decorators_aiopqueue/; python client.py )

pages:
  stage: deploy
  script:
  - pip install sphinx
  - (cd doc && make html); mv doc/_build/html public
  artifacts:
    paths:
    - public
  only:
  - main
